### ISSUE TITLE
v2.2.8 introduces SyntaxError: ':focus-visible' is not a valid selector

### ISSUE THREAD

**Issue by cbix** [dperini/nwsapi#110]
I noticed a similar regression as #108, one test using react-testing-library (→ jsdom) started failing with
```
SyntaxError: ':focus-visible' is not a valid selector

      at emit (node_modules/nwsapi/src/nwsapi.js:557:17)
      at compileSelector (node_modules/nwsapi/src/nwsapi.js:1288:11)
      at compile (node_modules/nwsapi/src/nwsapi.js:745:16)
      at collect (node_modules/nwsapi/src/nwsapi.js:1546:22)
      at _querySelectorAll (node_modules/nwsapi/src/nwsapi.js:1506:36)
      at Object._querySelector [as first] (node_modules/nwsapi/src/nwsapi.js:1412:14)
      at Array.Resolver (eval at compile (node_modules/nwsapi/src/nwsapi.js:760:17), <anonymous>:3:91)
      at match_assert (node_modules/nwsapi/src/nwsapi.js:1339:13)
      at Object._matches [as match] (node_modules/nwsapi/src/nwsapi.js:1357:16)
          at Array.forEach (<anonymous>)
          at Array.forEach (<anonymous>)
          at Array.forEach (<anonymous>)
      at closestPointerEventsDeclaration (node_modules/@testing-library/user-event/dist/cjs/utils/pointer/cssPointerEvents.js:16:38)
      at checkPointerEvents (node_modules/@testing-library/user-event/dist/cjs/utils/pointer/cssPointerEvents.js:36:25)
      at Object.assertPointerEvents (node_modules/@testing-library/user-event/dist/cjs/utils/pointer/cssPointerEvents.js:45:25)
      at Object.enter (node_modules/@testing-library/user-event/dist/cjs/system/pointer/pointer.js:57:34)
      at PointerHost.move (node_modules/@testing-library/user-event/dist/cjs/system/pointer/index.js:50:79)
      at pointerAction (node_modules/@testing-library/user-event/dist/cjs/pointer/index.js:64:39)
      at Object.pointer (node_modules/@testing-library/user-event/dist/cjs/pointer/index.js:32:15)
      at Object.asyncWrapper (node_modules/@testing-library/react/dist/pure.js:88:22)
```

If needed I can try to open a repo for reproducing this.

**Comment by TonyxSun** [comment]
Bump, also related to #54

**Comment by dperini** [comment]
@cbix @TonyxSun 
the fix has been applied, problem should be resolved in current master.
Maybe you can confirm this solves your problem.

**Comment by cbix** [comment]
@dperini I can confirm it's fixed on latest master, thanks! Would be awesome to see a release with that fix :)

**Comment by dperini** [comment]
@cbix I am almost there, 2.2.10 is ready to go.
You can help spot last minute mistakes
please checkout master and test it.
If you can !

**Comment by cbix** [comment]
@dperini nice, yea I checked out master and our tests all passed again without errors. Anyway like I said nwsapi for us was just the indirect dep through jsdom.
