### ISSUE TITLE
'' is not a valid selector

### ISSUE THREAD

**Issue by FedeTommi** [dperini/nwsapi#120]
I am using angular/components, which uses this library as a dependency. 
The filters on MatExpansionPanelHarness seem to be not working correctly.

On:

const expansionPanels = await loader.getHarness(MatExpansionPanelHarness.with({ disabled: true }));

I get the error:

SyntaxError: '' is not a valid selector
at emit (/node_modules/nwsapi/src/nwsapi.js:575:17)
at Object._querySelectorAll [as select] (/node_modules/nwsapi/src/nwsapi.js:1491:9)
at HTMLDivElementImpl.querySelectorAll (node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:78:26)
at HTMLDivElement.querySelectorAll (node_modules/jsdom/lib/jsdom/living/generated/Element.js:1119:58)
at Object.queryFn (node_modules/@angular/cdk/fesm2022/testing/testbed.mjs:622:39)
at TestbedHarnessEnvironment.getAllRawElements (node_modules/@angular/cdk/fesm2022/testing/testbed.mjs:770:41)

Please refer to: https://github.com/angular/components/issues/29454

**Comment by dperini** [comment]
All reported issues having the error similar t o "is not a valid selectors" had a common cause.
The nesting Regular Expression in the recently added :has() pseudo-class resolver was wrong.
Closing this now.
