### ISSUE TITLE
SyntaxError: ':is(:is(button, input)[type=submit], button:not([type])):not([disabled]):not([form])' is not a valid selector

### ISSUE THREAD

**Issue by Enes5519** [dperini/nwsapi#127]
I am using a button inside a custom elements library to submit a form. When I call `this.closest('form')` from inside that button, I get this error.

@testing-library/svelte@5.2.1
vitest@2.0.5
jsdom@25.0.0
nwsapi@2.2.12

Library: https://github.com/Trendyol/baklava/blob/next/src/components/button/bl-button.ts#L151

```
SyntaxError: ':is(:is(button, input)[type=submit], button:not([type])):not([disabled]):not([form])' is not a valid selector
    at emit (/Users/enes.yildirim/Projects/bc-advert-web-app/node_modules/nwsapi/src/nwsapi.js:575:17)
    at compileSelector (/Users/enes.yildirim/Projects/bc-advert-web-app/node_modules/nwsapi/src/nwsapi.js:1308:11)
    at compile (/Users/enes.yildirim/Projects/bc-advert-web-app/node_modules/nwsapi/src/nwsapi.js:762:16)
    at match_collect (/Users/enes.yildirim/Projects/bc-advert-web-app/node_modules/nwsapi/src/nwsapi.js:1366:16)
    at _matches (/Users/enes.yildirim/Projects/bc-advert-web-app/node_modules/nwsapi/src/nwsapi.js:1421:35)
    at Object._closest [as closest] (/Users/enes.yildirim/Projects/bc-advert-web-app/node_modules/nwsapi/src/nwsapi.js:1350:13)
    at HTMLElementImpl.closest (/Users/enes.yildirim/Projects/bc-advert-web-app/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:550:20)
    at e.closest (/Users/enes.yildirim/Projects/bc-advert-web-app/node_modules/jsdom/lib/jsdom/living/generated/Element.js:632:58)
    at HTMLFormElement.<anonymous> (file:///Users/enes.yildirim/Projects/bc-advert-web-app/node_modules/@trendyol/baklava/node_modules/element-internals-polyfill/dist/index.js:267:24)
    at HTMLFormElement.callTheUserObjectsOperation (/Users/enes.yildirim/Projects/bc-advert-web-app/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
```

**Comment by chenshuai2144** [comment]
same error

`SyntaxError: ':scope +.ant-select-item-option-selected:not(.ant-select-item-option-disabled))+.ant-select-item-option-selected:not(.ant-select-item-option-disabled' is not a valid selector`

vitest + @testing-library/react  只要使用 findAllByxxx 就会报错

**Comment by dperini** [comment]
@chenshuai2144

Yes the selector you showed above is wrong.

document.querySelector(':scope +.ant-select-item-option-selected:not(.ant-select-item-option-disabled))+.ant-select-item-option-selected:not(.ant-select-item-option-disabled'); 

the first :not() instance terminates with an extra parenthesis.

This is the corrected broken down corrected version:

document.querySelectorAll(':scope\
+.ant-select-item-option-selected\
:not(.ant-select-item-option-disabled)\
+.ant-select-item-option-selected\
:not(.ant-select-item-option-disabled)');

**Comment by theishinz-maersk** [comment]
For future records. I bypassed the issue by adding polyfill.
In jest.polyfills.js

```
import "element-internals-polyfill";
```

**Comment by martijnpieters** [comment]
@theishinz-maersk the syntax error seems correct to me:

```
SyntaxError: 'button[type=submit],input[type=submit],button:not([type])):not([disabled]):not([form]' is not a valid selector
                                                                       ^ what is that one doing here?
```

The selector is not correct since there's no open parenthesis to close.

**Comment by dperini** [comment]
There is no issue here, it is just a wrong syntax as explained in my previous post and from @martijnpieters comment.
It might have been confused with other errors during the addition of the :has() pseudo-class.
So this issue is now closed.
