### ISSUE TITLE
Last version is breaking my tests

### ISSUE THREAD

**Issue by arqex** [dperini/nwsapi#135]
ReferenceError: document is not defined

at ../../node_modules/nwsapi/src/nwsapi.js:216:21

And it's true, that line should use `doc.` or `global.document`, but `document` is really undefined.

**Comment by benclarkmck** [comment]
https://github.com/dperini/nwsapi/pull/134

**Comment by dm-gc** [comment]
I can confirm my tests run by downgrading to 2.2.13: `npm install nwsapi@2.2.13`

**Comment by Ganbin** [comment]
Wow, I speed half of my day finding out what would be the issue in my tests. The last package that I tried to downgrade was this one, and the update from `2.2.13` to `2.2.14` did the exact same thing. All my test that used the jsom environment were broken.

On my side I had a different error :
```
TypeError: list.map is not a function
 ❯ HTMLBodyElementImpl.querySelectorAll node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:80:66
 ❯ HTMLBodyElement.querySelectorAll node_modules/jsdom/lib/jsdom/living/generated/Element.js:1119:58
 ❯ queryAllByRole node_modules/@testing-library/dom/dist/queries/role.js:111:31
 ❯ node_modules/@testing-library/dom/dist/query-helpers.js:74:17
 ❯ node_modules/@testing-library/dom/dist/query-helpers.js:52:17
 ❯ node_modules/@testing-library/dom/dist/query-helpers.js:95:19
```

**Comment by RubenAWL** [comment]
same issues here, updating to the newest 2.2.15 solved the issues and tests are working again.

**Comment by marcelhohn** [comment]
Updating to 2.2.15 didn't solve this issue: https://github.com/thymikee/jest-preset-angular/issues/2883

**Comment by news-manishpatel** [comment]
Adding the following to our package json did it for us. 

```
 "overrides": {
    "nwsapi": "2.2.13"
  }
```

**Comment by maf248** [comment]
Hi! Please be more carefull next time. We only had nwsapi as sub-dependency for js-dom and we had to override like someone else suggested.

**Comment by dperini** [comment]
@maf248
Sure , will call before !
Out of pure sarcasm ... are you sure there isn't a different approach
that will let us avoid depending on my time, my humor or my capabilities ?
A simple checkbox that defer publishing until all dependencies have agreed and are satisfied.

**Comment by dperini** [comment]
@arqex 
yes the most adequate should have been 'doc'.
However in the hurry-up it was fixed slightly in a different way.
The next release will hopefully be like you said, but there are rewrites too.

**Comment by dperini** [comment]
@marcelhohn there has been another fix and 2.2.16 is released now.
Does it work for you ?

**Comment by imakecodes** [comment]
Same issue here

**Comment by unstubbable** [comment]
[Works for us](https://github.com/vercel/next.js/pull/73353), thank you!

**Comment by jenewland1999** [comment]
Can confirm 2.2.16 is working. after 2.2.14 and 2.2.15 stopped working. Thanks for the quick turn around time on this! 👍🏻

**Comment by imakecodes** [comment]
Its working again with the latest version (2.2.16), thanks nwsapi team!

**Comment by maf248** [comment]
> @maf248 Sure , will call before ! Out of pure sarcasm ... are you sure there isn't a different approach that will let us avoid depending on my time, my humor or my capabilities ? A simple checkbox that defer publishing until all dependencies have agreed and are satisfied.

No need to call, maybe improve code coverage, testing or something. I know shit happens, no need to get upset. We've dealt with our shit, just suggesting you deal with yours.

**Comment by weinnandhasanion** [comment]
Hi @dperini, thanks for the quick fix! Latest version has fixed the document is not defined error, but now there's a different one:

```
SyntaxError: 'input#1 input[type=checkbox]:checked' is not a valid selector
      888 |     expect(list).not.toHaveClass('cmp-dropdown-list-multiselect--hide');
      889 |
    > 890 |     const [option1] = screen.getAllByRole('checkbox', {
          |                              ^
      891 |       name: 'BIZ_AGENT',
      892 |     });
      893 |     const [save] = screen.getAllByRole('button', { name: 'Save' });
      at emit (node_modules/nwsapi/src/nwsapi.js:651:17)
      at _querySelectorAll (node_modules/nwsapi/src/nwsapi.js:1646:9)
      at Object._querySelector [as first] (node_modules/nwsapi/src/nwsapi.js:1555:14)
      at HTMLInputElementImpl.querySelector (node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:69:44)
      at HTMLInputElement.querySelector (node_modules/jsdom/lib/jsdom/living/generated/Element.js:1094:58)
```

**Comment by weinnandhasanion** [comment]
Hi @dperini, thanks for the quick turn around! The latest version has fixed the `document is not defined error` in our Jest tests, but now there's a different one:

```
SyntaxError: 'input#1 input[type=checkbox]:checked' is not a valid selector
      889 |
    > 890 |     const [option1] = screen.getAllByRole('checkbox', {
          |                              ^
      at emit (node_modules/nwsapi/src/nwsapi.js:651:17)
      at _querySelectorAll (node_modules/nwsapi/src/nwsapi.js:1646:9)
      at Object._querySelector [as first] (node_modules/nwsapi/src/nwsapi.js:1555:14)
      at HTMLInputElementImpl.querySelector (node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:69:44)
      at HTMLInputElement.querySelector (node_modules/jsdom/lib/jsdom/living/generated/Element.js:1094:58)
```

**Comment by dperini** [comment]
@maf248
> No need to call, maybe improve code coverage, testing or something. I know shit happens, no need to get upset. We've dealt with our shit, just suggesting you deal with yours.

Absolutely not upset, I just wanted to stress on the fact that "toNodeList()" was added on November 4 so I left almost one month for developers to test and report failures, discrepancies and regressions but as you can see I got nothing.

Then there is this one interesting discussion going on in Angular issues:
https://github.com/thymikee/jest-preset-angular/issues/2883#issuecomment-2507850487

Finally I can assure I am running thousands of tests both the new set from wpt and those specific from jsdom and my own set. It doesn't matter how many test I run for myself I will always be short on them, I could not follow all the depending projects in all these years.

But yes, from my side I am trying to change this, the remaining steps to achieve perfection is on developers shoulders.

To close this with positive aptitudes I am willing to invest more time writing documentation, speaking with the developers about the secret side of this to ensure the power of nwsapi is used in full, there are a lot of hidden functionalities which where not disclosed but they would be extremely useful for developers.

If you also think this is possible and necessary and you are willing to help, please help me set up some quick live meeting with the right developers in your organization and in the other teams/project too.

**Comment by thinkasany** [comment]
> #73351
Same issue here. https://github.com/ant-design/ant-design/actions/runs/12101023030/job/33740362018?pr=51844
<img width="1415" alt="image" src="https://github.com/user-attachments/assets/0727884c-9e40-4e0d-93c8-936da23236b9">

**Comment by dperini** [comment]
@thinkasany @weinnandhasanion 
please open a different issue and attach a minimal code snippet showing the problematic selector.
I wouldn't know where to start looking for the bug you revealed.
Thank you for reporting the issue.

**Comment by csvan** [comment]
In case anyone needs this info you can lock your dependency resolutions to the last working version like so (in your `package.json`):

NPM:

```
  "overrides": {
    "nwsapi": "2.2.13"
  }
```

Yarn

```
  "resolutions": {
    "nwsapi": "2.2.13"
  }
```

**Comment by dperini** [comment]
Using the "global.document" in this commit 3f5d682f00bb980ff23658277fb841d10e8133b4
fixed  the issue.

The toNodeList() helper remains disabled by default, needs a revisiting and improvements.

Can be enabled by a Config option.
