### ISSUE TITLE
':focus-visible' is not supported, yet claims to be in the wiki

### ISSUE THREAD

**Issue by sambehrens** [dperini/nwsapi#54]
I ran into an issue where I was using jsdom which uses nwsapi for matching selectors and it was giving me the error `SyntaxError: ':focus-visible' is not a valid selector`. It doesn't seem like I should be getting this error because [in the wiki for nwsapi](https://github.com/dperini/nwsapi/wiki/CSS-supported-selectors#user-action-pseudo-classes-selectors:~:text=has%20input%20focus-,E%3Afocus%2Dvisible,-an%20E%20element), it says that the `:focus-visible` is supported. 

Then I looked through the nwsapi repo and didn't see `focus-visible` where I thought it should exist. Here with the other user actions: https://github.com/dperini/nwsapi/blob/master/src/nwsapi.js#L83

It would be great if this could be supported. Alternatively, the documentation could be updated explaining that it is actually not supported and why.

Reproduce:

```html
<script
  type="text/javascript"
  src="https://cdn.jsdelivr.net/npm/nwsapi@2.2.0/src/nwsapi.js"
></script>
<script>
  NW.Dom.match(":focus-visible", document, () => {});
</script>
```

Results in `Uncaught DOMException: ':focus-visible' is not a valid selector`.

On another note, it looks like `focus-within` throws the same error, even though it looks like it is available in the source code. Not sure why that would be though.

**Comment by dospunk** [comment]
I'm having the same issue with `:focus-within` and jsdom as well. The error stack trace does come back to nwsapi 

The relevant lines of the stack trace are:
```
at emit (node_modules/nwsapi/src/nwsapi.js:570:17)
at compileSelector (node_modules/nwsapi/src/nwsapi.js:1310:11)
at compile (node_modules/nwsapi/src/nwsapi.js:758:16)
at match_collect (node_modules/nwsapi/src/nwsapi.js:1363:16)
at Object._matches [as match] (node_modules/nwsapi/src/nwsapi.js:1418:35)
```

**Comment by samschurter** [comment]
I've run into problems with `:focus-within` as well. Perhaps the issues are related to #47 for that selector.

**Comment by dospunk** [comment]
I'm still getting the `SyntaxError: ':focus-within' is not a valid selector` error on nwsapi@2.2.4

**Comment by dperini** [comment]
@dospunk 
you are correct ... reopening and working on it.
Thank you for reporting the problem.

**Comment by dperini** [comment]
@sambehrens @samschurter @dospunk 
I hope I did resolve this and nwsapi will be ready for 2.2.10 release.

**Comment by cbix** [comment]
@dperini apparently this just got reintroduced, likely with a react-testing-library minor version update on our project:
```
SyntaxError: 'button#:r3m:.types__StyledButton-sc-ws60qy-0 :focus-visible' is not a valid selector
[...]
      at emit (node_modules/nwsapi/src/nwsapi.js:651:17)
      at _querySelectorAll (node_modules/nwsapi/src/nwsapi.js:1646:9)
      at Object._querySelector [as first] (node_modules/nwsapi/src/nwsapi.js:1555:14)
      at HTMLButtonElement.value [as querySelector] (node_modules/@primer/react/lib/node_modules/@oddbird/popover-polyfill/dist/popover-fn.js:389:23)
      at Array.Resolver (eval at compile (node_modules/nwsapi/src/nwsapi.js:853:17), <anonymous>:3:67)
      at match_assert (node_modules/nwsapi/src/nwsapi.js:1482:13)
      at Object._matches [as match] (node_modules/nwsapi/src/nwsapi.js:1500:16)
          at Array.forEach (<anonymous>)
          at Array.forEach (<anonymous>)
      at getComputedStyleImplementation (node_modules/dom-accessibility-api/sources/accessible-name-and-description.ts:84:16)
      at isHidden (node_modules/dom-accessibility-api/sources/accessible-name-and-description.ts:570:4)
      at computeTextAlternative (node_modules/dom-accessibility-api/sources/accessible-name-and-description.ts:721:3)
      at computeAccessibleName (node_modules/dom-accessibility-api/sources/accessible-name.ts:40:31)
      at node_modules/@testing-library/dom/dist/queries/role.js:173:82
          at Array.filter (<anonymous>)
      at queryAllByRole (node_modules/@testing-library/dom/dist/queries/role.js:168:6)
      at node_modules/@testing-library/dom/dist/query-helpers.js:74:17
      at node_modules/@testing-library/dom/dist/query-helpers.js:52:17
      at node_modules/@testing-library/dom/dist/query-helpers.js:95:19
      at container.container (node_modules/@testing-library/dom/dist/query-helpers.js:87:14)
      at runWithExpensiveErrorDiagnosticsDisabled (node_modules/@testing-library/dom/dist/config.js:47:12)
      at checkCallback (node_modules/@testing-library/dom/dist/wait-for.js:124:77)
      at checkRealTimersCallback (node_modules/@testing-library/dom/dist/wait-for.js:118:16)
```
